# Copy this file to config.yml to get started and then add your own configuration.
# Full documentation here: https://github.com/CryptoSignal/crypto-signal/blob/master/docs/config.md

settings:
  update_interval: 200
  market_pairs:
    - ETH/USDT
    - BNB/USDT
    - LTC/USDT
    - QTUM/USDT
    - ADA/USDT
    - XRP/USDT
    - EOS/USDT
    - IOTA/USDT
    - XLM/USDT
    - ONT/USDT
    - TRX/USDT
    - ETC/USDT
    - ICX/USDT
    - NULS/USDT
    - VET/USDT
    - USDC/USDT
    - LINK/USDT
    - WAVES/USDT
    - ONG/USDT
    - HOT/USDT
    - ZIL/USDT
    - ZRX/USDT
    - FET/USDT
    - BAT/USDT
    - XMR/USDT
    - ZEC/USDT
    - IOST/USDT
    - CELR/USDT
    - DASH/USDT
    - OMG/USDT
    - THETA/USDT
    - ENJ/USDT
    - MITH/USDT
    - MATIC/USDT
    - ATOM/USDT
    - TFUEL/USDT
    - ONE/USDT
    - FTM/USDT
    - ALGO/USDT
    - GTO/USDT
    - DOGE/USDT
    - DUSK/USDT
    - ANKR/USDT
    - WIN/USDT
    - COS/USDT
    - MTL/USDT
    - TOMO/USDT
    - DENT/USDT
    - MFT/USDT
    - KEY/USDT
    - DOCK/USDT
    - WAN/USDT
    - FUN/USDT
    - CVC/USDT
    - CHZ/USDT
    - BAND/USDT
    - BUSD/USDT
    - BEAM/USDT
    - XTZ/USDT
    - REN/USDT
    - RVN/USDT
    - HBAR/USDT
    - NKN/USDT
    - STX/USDT
    - KAVA/USDT
    - ARPA/USDT
    - IOTX/USDT
    - RLC/USDT
    - CTXC/USDT
    - BCH/USDT
    - TROY/USDT
    - FTT/USDT
    - OGN/USDT
    - TCT/USDT
    - BTS/USDT
    - BNT/USDT
    - LTO/USDT
    - MBL/USDT
    - COTI/USDT
    - STPT/USDT
    - SOL/USDT
    - CTSI/USDT
    - HIVE/USDT
    - CHR/USDT
    - MDT/USDT
    - STMX/USDT
    - KNC/USDT
    - LRC/USDT
    - PNT/USDT
    - COMP/USDT
    - SC/USDT
    - SNX/USDT
    - DGB/USDT
    - SXP/USDT
    - MKR/USDT
    - STORJ/USDT
    - MANA/USDT
    - BAL/USDT
    - BLZ/USDT
    - JST/USDT
    - SRM/USDT
    - ANT/USDT
    - CRV/USDT
    - SAND/USDT
    - OCEAN/USDT
    - NMR/USDT
    - DOT/USDT
    - LUNA/USDT
    - RSR/USDT
    - PAXG/USDT
    - WNXM/USDT
    - TRB/USDT
    - SUSHI/USDT
    - KSM/USDT
    - EGLD/USDT
    - DIA/USDT
    - RUNE/USDT
    - UMA/USDT
    - UNI/USDT
    - NBS/USDT
    - OXT/USDT
    - SUN/USDT
    - AVAX/USDT
    - HNT/USDT
    - ORN/USDT
    - UTK/USDT
    - XVS/USDT
    - ALPHA/USDT
    - AAVE/USDT
    - NEAR/USDT
    - FIL/USDT
    - INJ/USDT
    - AUDIO/USDT
    - CTK/USDT
    - AKRO/USDT
    - AXS/USDT
    - DNT/USDT
    - UNFI/USDT
    - ROSE/USDT
    - AVA/USDT
    - XEM/USDT
    - SKL/USDT
    - GRT/USDT
    - 1INCH/USDT
    - REEF/USDT
    - CELO/USDT
    - TRU/USDT
    - CKB/USDT
    - TWT/USDT
    - LIT/USDT
    - SFP/USDT
    - DODO/USDT
    - CAKE/USDT
    - BADGER/USDT
    - OM/USDT
    - POND/USDT
    - ALICE/USDT
    - LINA/USDT
    - SUPER/USDT
    - PUNDIX/USDT
    - TLM/USDT
    - BAR/USDT
    - BAKE/USDT
    - SLP/USDT
    - SHIB/USDT
    - ICP/USDT
    - AR/USDT
    - POLS/USDT
    - MDX/USDT
    - MASK/USDT
    - LPT/USDT
    - GTC/USDT
    - ERN/USDT
    - KLAY/USDT
    - PHA/USDT
    - BOND/USDT
    - MLN/USDT
    - C98/USDT
    - CLV/USDT
    - QNT/USDT
    - FLOW/USDT
    - TVK/USDT
    - MINA/USDT
    - RAY/USDT
    - QUICK/USDT
    - MBOX/USDT
    - WAXP/USDT
    - TRIBE/USDT
    - XEC/USDT
    - DYDX/USDT
    - IDEX/USDT
    - GALA/USDT
    - YGG/USDT
    - AGLD/USDT
    - RAD/USDT
    - BETA/USDT
    - RARE/USDT
    - CHESS/USDT
    - DAR/USDT
    - BNX/USDT
    - ENS/USDT
    - QI/USDT
    - JASMY/USDT
    - PYR/USDT
    - RNDR/USDT
    - BICO/USDT
    - FLUX/USDT
    - VOXEL/USDT
    - PEOPLE/USDT
    - API3/USDT
    - ANC/USDT
    - WOO/USDT
    - T/USDT
    - ASTR/USDT
    - GMT/USDT
    - KDA/USDT
    - APE/USDT
    - BSW/USDT
    - MOB/USDT
    - NEXO/USDT
    - REI/USDT
    - GAL/USDT
    - OP/USDT
    - USDT/TRY
    - WAXP/USDT

exchanges:
  binance:
    required:
      enabled: true
